In [1]:
import torch
import torch.nn as nn

In [9]:
class SimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out



**Creating dataset**

In [7]:
dataset=torch.rand(20,5)
dataset

tensor([[0.1574, 0.5128, 0.9157, 0.0471, 0.7910],
        [0.3078, 0.0297, 0.2858, 0.4974, 0.9885],
        [0.4224, 0.5379, 0.8188, 0.9424, 0.2481],
        [0.8699, 0.4137, 0.3509, 0.9268, 0.6464],
        [0.8405, 0.5793, 0.2091, 0.0490, 0.7654],
        [0.8582, 0.1810, 0.4983, 0.8440, 0.7098],
        [0.8608, 0.0222, 0.2925, 0.5424, 0.3279],
        [0.3199, 0.4054, 0.0723, 0.0010, 0.9580],
        [0.0890, 0.0400, 0.4829, 0.5507, 0.1500],
        [0.1303, 0.4919, 0.1435, 0.5886, 0.0537],
        [0.0577, 0.3082, 0.6847, 0.8807, 0.0499],
        [0.6847, 0.5073, 0.2530, 0.8053, 0.3960],
        [0.7127, 0.3141, 0.5979, 0.8788, 0.6312],
        [0.4460, 0.1785, 0.6671, 0.3625, 0.7818],
        [0.3388, 0.1222, 0.6739, 0.7389, 0.2390],
        [0.0025, 0.6349, 0.4512, 0.7619, 0.7981],
        [0.0801, 0.5534, 0.6985, 0.9523, 0.3552],
        [0.8656, 0.7371, 0.5777, 0.5671, 0.9911],
        [0.3738, 0.2836, 0.6721, 0.9886, 0.1776],
        [0.2711, 0.6037, 0.1005, 0.4572, 0.5535]])

**Create Model**

In [10]:
model=SimpleNN(dataset.shape[1])

In [11]:
model

SimpleNN(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

**Forward Pass**

In [12]:
model(dataset)

tensor([[0.3972],
        [0.4052],
        [0.3966],
        [0.4029],
        [0.4134],
        [0.3923],
        [0.3954],
        [0.4181],
        [0.4013],
        [0.4224],
        [0.4009],
        [0.4124],
        [0.3945],
        [0.3930],
        [0.3925],
        [0.4170],
        [0.4065],
        [0.4034],
        [0.3961],
        [0.4200]], grad_fn=<SigmoidBackward0>)

In [18]:
for name, param in model.named_parameters():
  print(name, param.shape)

network.0.weight torch.Size([3, 5])
network.0.bias torch.Size([3])
network.2.weight torch.Size([1, 3])
network.2.bias torch.Size([1])


In [20]:
for name, param in model.named_parameters():
  print("Name:", name)
  print(param)
  print("-----------------------")


Name: network.0.weight
Parameter containing:
tensor([[-0.4259, -0.1634,  0.0954,  0.3067,  0.2132],
        [ 0.0623,  0.1673, -0.2814, -0.1734, -0.3787],
        [ 0.2077, -0.3022,  0.4220, -0.0152, -0.0258]], requires_grad=True)
-----------------------
Name: network.0.bias
Parameter containing:
tensor([-0.2301,  0.3028,  0.0100], requires_grad=True)
-----------------------
Name: network.2.weight
Parameter containing:
tensor([[-0.0352,  0.0785, -0.3408]], requires_grad=True)
-----------------------
Name: network.2.bias
Parameter containing:
tensor([-0.3311], requires_grad=True)
-----------------------


In [21]:
!pip install torchinfo

In [22]:
from torchinfo import summary
summary(model,input_size=(20,5))

Layer (type:depth-idx)                   Output Shape              Param #
SimpleNN                                 [20, 1]                   --
├─Sequential: 1-1                        [20, 1]                   --
│    └─Linear: 2-1                       [20, 3]                   18
│    └─ReLU: 2-2                         [20, 3]                   --
│    └─Linear: 2-3                       [20, 1]                   4
│    └─Sigmoid: 2-4                      [20, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00